# This is a basic workflow to help you get started with Actions

name: Deploy To Bintray

# Controls when the action will run. 
on:
  push:
    tags:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - name: Gradle Android
        # You may pin to the exact commit or the version.
        # uses: Raul6469/android-gradle-action@b8fc7c7bde2562a4578b7e1bd996cc78d841638e
        uses: Raul6469/android-gradle-action@2.0.0
        env:
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
        with:
          # The ./gradlew command arguments
          script: assembleRelease bintrayUpload
